Text sizescale
elementary/switchboard-plug-pantheon-shell pull request #298
Opened 2021-11-01 22:19 UTC by danrabbit

- [ ] Based on #297

Fixes #289
Fixes #248

2021-11-09 03:45 UTC, cassidyjames requested changes
Need to fix keyboard interactivity, I think I messed up resolving merge conflicts (and will try to fix that), and I have a question about the design:

Should we just go with the scale + spinbutton like we do in both Keyboard and Mouse & Touchpad settings? It seems like this is an appropriate place and would make it easier if you know a specific text scale works well on your machine versus having to just guess based on the current design. I also think it would let us address my other inline comment about the start and end marks, since the scale would be even more self-evident.

2021-11-09 03:45 UTC, cassidyjames commented on src/Views/Text.vala
> +        text_size_scale.button_release_event.connect (() => {
So the problem with this approach is that it's not accessible with the keyboard. Gotta keep that. :smile:

2021-11-09 03:45 UTC, cassidyjames commented on src/Views/Text.vala
> +        text_size_scale.add_mark (1.45, Gtk.PositionType.BOTTOM, _("Largest"));
This makes me wonder if we need the small and largest marks at all; they're kind of self-evident based on the design, and we would avoid this funkiness.

2021-11-09 03:46 UTC, danrabbit commented
Yeah good call about the spin button

2021-11-10 20:47 UTC, danrabbit commented
@cassidyjames thanks for the thorough review here! I changed things to match the design of scale + spinbutton we have in other views like Mouse & Touchpad. So, removed the labels, notches on top. I also changed the set method from button release on the scale to a timeout on the adjustment. This fixes the keyboard case and should still have the same effect of keeping the UI from doing a stuttering resize while you're still dragging

2021-11-16 17:46 UTC, cassidyjames approved these changes
Nice work, this seems a lot better.

2021-11-16 17:48 UTC, merged