Basic setup for settings sidebar
elementary/switchboard-plug-pantheon-shell pull request #299
Opened 2021-11-05 19:37 UTC by danrabbit

![Screenshot from 2021-11-05 12 34 22](https://user-images.githubusercontent.com/7277719/140568501-4f8477e3-2aba-4e33-9704-b158bc543623.png)

Todo:
- [ ] https://github.com/elementary/icons/pull/1053
- [ ] https://github.com/elementary/icons/issues/1054
- [ ] Change either wallpaper or dock/panel icon
- [ ] Multitasking view forces the width of the window

2021-12-19 11:09 UTC, hanaral commented
Something about this layout seems off, maybe it's that the current one is more natural to read (I think because it's above the page and horizontally laid out)

2022-07-03 16:21 UTC, jeremypw commented
@danrabbit  I have fixed conflicts with master.  One problem I have noticed with using Granite.SimpleSettingsPage (a scrolled window) with Multi-tasking View is that if the window height is such as to require scrolling then if you scroll on the content area you will at some point enter a combo and start changing the options instead of scrolling - which is definitely undesirable.  The simplest solution is to set a minimum height on the Settings window sufficient that scrolling is never required on Multitasking View.

2022-07-03 17:04 UTC, jeremypw commented
I have proposed a change to Switchboard (https://github.com/elementary/switchboard/pull/242) so that this view does not have to scroll and all the settings are visible when it is opened.

2022-07-03 17:14 UTC, jeremypw requested changes
The code looks good and the change makes sense in the context of a strategy of moving all the plugs using a Stack to a SettingsSidebar (as many are already).

The screenshots need updating.

2023-05-02 11:28 UTC, lenemter reviewed
I get warnings when I close the System Settings app in this branch:
```
** (io.elementary.switchboard:4237): CRITICAL **: 20:14:27.643: granite_settings_sidebar_row_get_page: assertion 'self != NULL' failed

(io.elementary.switchboard:4237): Gtk-CRITICAL **: 20:14:27.643: gtk_stack_set_visible_child: assertion 'GTK_IS_WIDGET (child)' failed
```

Overall I think this is a step in a good direction but it needs more polishing. For example: 
1. 'Wallpaper' and 'Dock & Panel' pages shouldn't use the same icon;
2. Appearance tab looks weird compared to other pages because of it's long description while other pages don't have it at all;
3. IMO It would be nice if every page's max width was the same and these header labels wouldn't jump around

2023-05-02 11:30 UTC, lenemter commented on src/Views/Appearance.vala
>              grid.attach (prefer_style_box, 0, 2, 2);
This grid's attaches should start with `0, 0`, not from `0, 2` straightaway.

2023-05-05 13:17 UTC, 1280px commented
> Something about this layout seems off, maybe it's that the current one is more natural to read (I think because it's above the page and horizontally laid out)

It also sacrifices more horizontal space, yet doesn't resolve the problem of vertical space usage (mainly because of the headers, which don't provide any useful information). Considering the sidebar doesn't provide neither the grouping by categories nor the state, I think it will might also make the uI less consistent?

2024-05-18 15:50 UTC, closed without merging