Selected wallpaper check: follow accent color
elementary/switchboard-plug-pantheon-shell pull request #323
Opened 2022-08-08 13:03 UTC by lenemter

Closes #274 

Uses radio button instead of icon

![image](https://user-images.githubusercontent.com/80143868/183424256-a245c1bc-8654-4d51-88cb-886e10d7e3e9.png)

2022-08-08 14:44 UTC, jeremypw requested changes
@lenemter Is it possible to find a solution using Gtk.CheckButton?  Gtk.RadioButton is deprecated and not present in Gtk4.

2022-08-08 15:34 UTC, jeremypw commented
@lenemter On further thought, I am not sure whether a button is appropriate as the tick is really an emblem - it is not an active button that can be toggled.  Maybe better to color the image?

2022-08-09 04:37 UTC, lenemter commented
So, I tried to color an image. I took selection-checked icon, removed background from svg and added background in css. Result:

![image](https://user-images.githubusercontent.com/80143868/183561685-4f449208-fd6d-457d-9795-6714f6acabc5.png)

 What do you think looks better?

2022-08-09 07:50 UTC, jeremypw approved these changes

2022-08-09 07:50 UTC, merged